allowBuilds:
  '@swc/core': true
  esbuild: true
  msw: true

onlyBuiltDependencies:
  - '@swc/core'
  - '@swc/core@1.13.5'
  - esbuild
  - esbuild@0.21.5
  - esbuild@0.25.11
  - msw
  - msw@2.13.4(@types/node@22.18.12)(typescript@5.9.3)
